"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-06-29 12:39:52.384743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_target', 'audit_log', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_audit_log_tenant_occurred', 'audit_log', ['tenant_id', 'occurred_at'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('employee_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drivers_tenant_id', 'drivers', ['tenant_id'], unique=False)
    op.create_table('trucks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('dashcam_serial', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'label', name='uq_trucks_tenant_label')
    )
    op.create_index('ix_trucks_tenant_id', 'trucks', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('requester_name', sa.String(), nullable=True),
    sa.Column('requester_org', sa.String(), nullable=True),
    sa.Column('incident_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'under_review', 'approved', 'closed', name='case_status'), server_default='open', nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'number', name='uq_cases_tenant_number')
    )
    op.create_index('ix_cases_tenant_id', 'cases', ['tenant_id'], unique=False)
    op.create_index('ix_cases_tenant_status', 'cases', ['tenant_id', 'status'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('dashcam_firmware', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clips_tenant_id', 'clips', ['tenant_id'], unique=False)
    op.create_index('ix_clips_tenant_truck_started', 'clips', ['tenant_id', 'truck_id', 'started_at'], unique=False)
    op.create_table('case_clips',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('clip_id', sa.UUID(), nullable=False),
    sa.Column('attached_by', sa.UUID(), nullable=False),
    sa.Column('attached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attached_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'clip_id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('clip_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.Enum('harsh_brake', 'harsh_accel', 'collision', 'lane_departure', 'speeding', 'distracted_driving', name='event_type'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='event_severity'), nullable=False),
    sa.Column('telemetry', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_tenant_id', 'events', ['tenant_id'], unique=False)
    op.create_index('ix_events_tenant_severity_occurred', 'events', ['tenant_id', 'severity', 'occurred_at'], unique=False)
    op.create_index('ix_events_tenant_truck_occurred', 'events', ['tenant_id', 'truck_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_tenant_truck_occurred', table_name='events')
    op.drop_index('ix_events_tenant_severity_occurred', table_name='events')
    op.drop_index('ix_events_tenant_id', table_name='events')
    op.drop_table('events')
    op.drop_table('case_clips')
    op.drop_index('ix_clips_tenant_truck_started', table_name='clips')
    op.drop_index('ix_clips_tenant_id', table_name='clips')
    op.drop_table('clips')
    op.drop_index('ix_cases_tenant_status', table_name='cases')
    op.drop_index('ix_cases_tenant_id', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_trucks_tenant_id', table_name='trucks')
    op.drop_table('trucks')
    op.drop_index('ix_drivers_tenant_id', table_name='drivers')
    op.drop_table('drivers')
    op.drop_table('tenants')
    op.drop_index('ix_audit_log_tenant_occurred', table_name='audit_log')
    op.drop_index('ix_audit_log_target', table_name='audit_log')
    op.drop_table('audit_log')
    # Drop Postgres ENUM types — Alembic autogen does not handle these on
    # downgrade. Listed after table drops since types are referenced by columns.
    sa.Enum(name='event_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='event_severity').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='case_status').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
